source :rubygems

gem 'assignable_values'
gem 'rails', '~>2.3'
gem 'rspec', '~>1.3'
gem 'rspec-rails', '~>1.3'
gem 'shoulda-matchers', '<2'
gem 'sqlite3'
gem 'rspec_candy'
gem 'ruby-debug', :platforms => :mri_18
gem 'test-unit', '~>1.2', :platforms => :ruby_19
gem 'hoe', '=2.8.0', :platforms => :ruby_19

gem 'consul', :path => '../..'
