source :rubygems

gem 'assignable_values'
gem 'rails', '~>2.3'
gem 'rspec', '~>1.3'
gem 'rspec-rails', '~>1.3'
gem 'shoulda-matchers'
gem 'sqlite3'
gem 'rspec_candy'
gem 'ruby-debug'

gem 'consul', :path => '../..'
