source 'https://rubygems.org'

gem 'minitest' # fix MiniTest deprecation warnings
gem 'assignable_values'
gem 'rails', '4.1.0'
gem 'rspec'
gem 'rspec-rails'
gem 'shoulda-matchers'
gem 'sqlite3'
gem 'rspec_candy'

gem 'consul', :path => '../..'
