source 'https://rubygems.org'

gem 'assignable_values'
gem 'rails', '~>3.2.0'
gem 'rspec'
gem 'rspec-rails'
gem 'shoulda-matchers', '<2'
gem 'sqlite3'
gem 'rspec_candy'

gem 'consul', :path => '../..'
