source :rubygems

gem 'assignable_values'
gem 'rails', '~>3.2.0'
gem 'rspec'
gem 'rspec-rails'
gem 'shoulda-matchers'
gem 'sqlite3'
gem 'rspec_candy'
gem 'ruby-debug'
gem 'database_cleaner'

gem 'consul', :path => '../..'
